# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Ulik' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ulik

pod 'SnapKit', '~> 5.0.0'

end

# add the Firebase pod for Google Analytics
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods