# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Ulik' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ulik

pod 'SnapKit', '~> 5.0.0'

end
